/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApoioRouteImport } from './routes/apoio'
import { Route as BackofficeIndexRouteImport } from './routes/backoffice/index'
import { Route as VagasVagaIdRouteImport } from './routes/vagas/$vagaId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApoioRoute = ApoioRouteImport.update({
  id: '/apoio',
  path: '/apoio',
  getParentRoute: () => rootRouteImport,
} as any)
const BackofficeIndexRoute = BackofficeIndexRouteImport.update({
  id: '/backoffice/',
  path: '/backoffice/',
  getParentRoute: () => rootRouteImport,
} as any)
const VagasVagaIdRoute = VagasVagaIdRouteImport.update({
  id: '/vagas/$vagaId',
  path: '/vagas/$vagaId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apoio': typeof ApoioRoute
  '/vagas/$vagaId': typeof VagasVagaIdRoute
  '/backoffice/': typeof BackofficeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apoio': typeof ApoioRoute
  '/vagas/$vagaId': typeof VagasVagaIdRoute
  '/backoffice': typeof BackofficeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apoio': typeof ApoioRoute
  '/vagas/$vagaId': typeof VagasVagaIdRoute
  '/backoffice/': typeof BackofficeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/apoio' | '/vagas/$vagaId' | '/backoffice/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/apoio' | '/vagas/$vagaId' | '/backoffice'
  id: '__root__' | '/' | '/apoio' | '/vagas/$vagaId' | '/backoffice/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApoioRoute: typeof ApoioRoute
  VagasVagaIdRoute: typeof VagasVagaIdRoute
  BackofficeIndexRoute: typeof BackofficeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apoio': {
      id: '/apoio'
      path: '/apoio'
      fullPath: '/apoio'
      preLoaderRoute: typeof ApoioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backoffice/': {
      id: '/backoffice/'
      path: '/backoffice'
      fullPath: '/backoffice/'
      preLoaderRoute: typeof BackofficeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vagas/$vagaId': {
      id: '/vagas/$vagaId'
      path: '/vagas/$vagaId'
      fullPath: '/vagas/$vagaId'
      preLoaderRoute: typeof VagasVagaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApoioRoute: ApoioRoute,
  VagasVagaIdRoute: VagasVagaIdRoute,
  BackofficeIndexRoute: BackofficeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
